export const PARAMETER_INFO: Record<string, string> = {
	'boreDiameter': 'The internal diameter of the flute tube. Larger bore produces louder, darker tones while smaller bore creates brighter, focused sound.',
	'wallThickness': 'Thickness of the flute tube walls. Affects resonance and structural integrity. Thicker walls produce warmer tones but require more material.',
	'hasThumbHole': 'Adds a thumb hole on the back of the flute for extended note range and chromatic playing.',
	'thumbHoleDiameter': 'Diameter of the thumb hole. Smaller holes are easier to half-hole for chromatic notes.',
	'thumbHoleAngle': 'Angular position of the thumb hole. 0 degrees places it at the bottom, 90 degrees places it on the side.',
	'overhangLength': 'Distance the tube extends beyond the embouchure hole towards the closed end. Affects tuning and tone quality.',
	'corkDistance': 'Distance from the embouchure hole center to the cork/end cap. Critical for proper tuning and response.',
	'corkThickness': 'Thickness of the cork or end cap material. Affects the sealed end\'s acoustic properties.',
	'embouchureHoleLength': 'Length dimension of the embouchure hole (blow hole). Larger holes allow more air flow but require more breath control.',
	'embouchureHoleWidth': 'Width dimension of the embouchure hole. Combined with length, determines the total opening area and playing characteristics.',
	'lipCoveragePercent': 'Percentage of the embouchure hole covered by the player\'s lips. Affects tone color and pitch stability.',
	'numberOfToneHoles': 'Number of finger holes for playing different notes. More holes enable extended range and chromatic notes.',
	'fundamentalFrequency': 'The lowest pitch the flute produces with all holes closed. Determines the key and range of the instrument.',
	'toneHoleDiameter': 'The diameter of each tone hole. Larger holes produce louder sound and affect tuning. Typical range is 5-12mm.',
	'toneHolePitch': 'The pitch (in cents above fundamental) that this hole produces when opened. Based on the diatonic scale.',
	'toneHoleDistance': 'Distance from the base of the flute to the center of this tone hole. Calculated based on acoustics.',
	'toneHoleCutoffRatio': 'Ratio of the hole\'s cutoff frequency to the target note frequency. Affects tone quality and response characteristics.',
	'toneHoleFilletRadius': 'Radius of the fillet (rounded edge) applied to tone holes. Larger fillets are easier to print and more comfortable to play.',
	'connectorLength': 'Length of connector pieces used to join flute sections. Longer connectors provide stronger joints but add weight.',
	'numberOfCuts': 'Number of cuts to divide the flute into printable sections. More cuts allow printing on smaller beds but require more assembly.',
	'cutDistance': 'Distance from the base of flute to each cut location. Determines where the flute will be divided into sections.'
};
